name: Auto Sign-in for BBS

on:
  schedule:
    - cron: '10 23 * * *'
  workflow_dispatch:

jobs:
  sign_in_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4      # 升级到 v4

      - name: Set up Python
        uses: actions/setup-python@v5  # 升级到 v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install playwright

      - name: Install Playwright Browsers
        run: |
          playwright install chromium

      - name: Run sign-in script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          WX_ROBOT_WEBHOOK: ${{ secrets.WX_ROBOT_WEBHOOK }}
        run: python sign_ikuuu.py
